/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n": typeof types.ChangePasswordDocument,
    "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n": typeof types.ForgotPasswordDocument,
    "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiateEmailChangeDocument,
    "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiatePhoneChangeDocument,
    "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        role\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      role\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": typeof types.RegisterDocument,
    "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n": typeof types.ResendOtpDocument,
    "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n": typeof types.ResetPasswordDocument,
    "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n": typeof types.VerifyEmailChangeDocument,
    "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n": typeof types.VerifyOtpDocument,
    "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": typeof types.VerifyPasswordResetOtpDocument,
    "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n": typeof types.VerifyPhoneChangeDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n": typeof types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n": typeof types.CategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n": typeof types.CitiesDocument,
    "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n": typeof types.CreateContactMessageDocument,
    "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": typeof types.CreateListingDocument,
    "\n  query listing($listingId: String!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n      }\n    }\n  }\n": typeof types.ListingDocument,
    "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n": typeof types.ListingsDocument,
    "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n": typeof types.MyListingsDocument,
    "\n  mutation removeListing($removeListingId: String!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n": typeof types.RemoveListingDocument,
    "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": typeof types.UpdateListingDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n": typeof types.GetSettingDocument,
    "\n  query me {\n    me {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": typeof types.MeDocument,
    "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n": typeof types.RemoveAvatarDocument,
    "\n  mutation signContract($input: SignContractInput!) {\n    signContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": typeof types.SignContractDocument,
    "\n  mutation terminateContract($terminationReason: String!) {\n    terminateContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": typeof types.TerminateContractDocument,
    "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n": typeof types.UpdateUserDocument,
};
const documents: Documents = {
    "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n": types.ChangePasswordDocument,
    "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n": types.ForgotPasswordDocument,
    "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiateEmailChangeDocument,
    "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiatePhoneChangeDocument,
    "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        role\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      role\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": types.RegisterDocument,
    "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n": types.ResendOtpDocument,
    "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n": types.ResetPasswordDocument,
    "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n": types.VerifyEmailChangeDocument,
    "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n": types.VerifyOtpDocument,
    "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": types.VerifyPasswordResetOtpDocument,
    "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n": types.VerifyPhoneChangeDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n": types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n": types.CategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n": types.CitiesDocument,
    "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n": types.CreateContactMessageDocument,
    "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": types.CreateListingDocument,
    "\n  query listing($listingId: String!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n      }\n    }\n  }\n": types.ListingDocument,
    "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n": types.ListingsDocument,
    "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n": types.MyListingsDocument,
    "\n  mutation removeListing($removeListingId: String!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n": types.RemoveListingDocument,
    "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": types.UpdateListingDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n": types.GetSettingDocument,
    "\n  query me {\n    me {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": types.MeDocument,
    "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n": types.RemoveAvatarDocument,
    "\n  mutation signContract($input: SignContractInput!) {\n    signContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": types.SignContractDocument,
    "\n  mutation terminateContract($terminationReason: String!) {\n    terminateContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": types.TerminateContractDocument,
    "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n": types.UpdateUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        role\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        role\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      role\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      role\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"): (typeof documents)["\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n"): (typeof documents)["\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query listing($listingId: String!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query listing($listingId: String!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        userId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeListing($removeListingId: String!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation removeListing($removeListingId: String!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      userId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n"): (typeof documents)["\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query me {\n    me {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"): (typeof documents)["\n  query me {\n    me {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n"): (typeof documents)["\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation signContract($input: SignContractInput!) {\n    signContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"): (typeof documents)["\n  mutation signContract($input: SignContractInput!) {\n    signContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation terminateContract($terminationReason: String!) {\n    terminateContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"): (typeof documents)["\n  mutation terminateContract($terminationReason: String!) {\n    terminateContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      role\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        userId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;