/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n": typeof types.ChangePasswordDocument,
    "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n": typeof types.ForgotPasswordDocument,
    "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiateEmailChangeDocument,
    "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiatePhoneChangeDocument,
    "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": typeof types.RegisterDocument,
    "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n": typeof types.ResendOtpDocument,
    "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n": typeof types.ResetPasswordDocument,
    "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n": typeof types.VerifyEmailChangeDocument,
    "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n": typeof types.VerifyOtpDocument,
    "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": typeof types.VerifyPasswordResetOtpDocument,
    "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n": typeof types.VerifyPhoneChangeDocument,
    "\n  mutation changeProviderPassword($input: ChangePasswordInput!) {\n    changeProviderPassword(input: $input)\n  }\n": typeof types.ChangeProviderPasswordDocument,
    "\n  mutation forgotProviderPassword($input: ForgotPasswordInput!) {\n    forgotProviderPassword(input: $input)\n  }\n": typeof types.ForgotProviderPasswordDocument,
    "\n  mutation initiateProviderEmailChange($input: ChangeEmailInput!) {\n    initiateProviderEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiateProviderEmailChangeDocument,
    "\n  mutation initiateProviderPhoneChange($input: ChangePhoneInput!) {\n    initiateProviderPhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": typeof types.InitiateProviderPhoneChangeDocument,
    "\n  mutation loginProvider($input: LoginProviderInput!) {\n    loginProvider(input: $input) {\n      accessToken\n      provider {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n": typeof types.LoginProviderDocument,
    "\n  mutation registerProvider($input: RegisterProviderInput!) {\n    registerProvider(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": typeof types.RegisterProviderDocument,
    "\n  mutation resendProviderOtp($input: ResendOtpInput!) {\n    resendProviderOtp(input: $input)\n  }\n": typeof types.ResendProviderOtpDocument,
    "\n  mutation resetProviderPassword($input: ResetPasswordWithTokenInput!) {\n    resetProviderPassword(input: $input)\n  }\n": typeof types.ResetProviderPasswordDocument,
    "\n  mutation verifyProviderEmailChange($input: VerifyChangeEmailInput!) {\n    verifyProviderEmailChange(input: $input)\n  }\n": typeof types.VerifyProviderEmailChangeDocument,
    "\n  mutation verifyProviderOtp($input: VerifyOtpInput!) {\n    verifyProviderOtp(input: $input)\n  }\n": typeof types.VerifyProviderOtpDocument,
    "\n  mutation verifyProviderPasswordResetOtp(\n    $input: VerifyPasswordResetOtpInput!\n  ) {\n    verifyProviderPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": typeof types.VerifyProviderPasswordResetOtpDocument,
    "\n  mutation verifyProviderPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyProviderPhoneChange(input: $input)\n  }\n": typeof types.VerifyProviderPhoneChangeDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n": typeof types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n": typeof types.CategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n": typeof types.CitiesDocument,
    "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n": typeof types.CreateContactMessageDocument,
    "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": typeof types.CreateListingDocument,
    "\n  query listing($listingId: ID!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n        isActive\n        emailVerified\n        email\n        createdAt\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n": typeof types.ListingDocument,
    "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n": typeof types.ListingsDocument,
    "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n": typeof types.MyListingsDocument,
    "\n  mutation removeListing($removeListingId: ID!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n": typeof types.RemoveListingDocument,
    "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": typeof types.UpdateListingDocument,
    "\n  query meProvider {\n    meProvider {\n      address\n      avatarFilename\n      bankName\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        image\n        nameAr\n        nameEn\n        publicId\n        rulesAr\n        rulesEn\n        updatedAt\n      }\n      cityId\n      commercialName\n      commercialRegistrationFilename\n      commercialRegistrationNumber\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      createdAt\n      deactivationReason\n      deleteReason\n      deletedAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      withAbsher\n      updatedAt\n      status\n      signedContract {\n        acceptedRulesAr\n        acceptedRulesEn\n        contractExpiresAt\n        contractSignedAt\n        createdAt\n        id\n        platformManagerName\n        platformManagerSignature\n        providerId\n        publicId\n        serviceProviderSignature\n        status\n        terminationReason\n        updatedAt\n      }\n      publicId\n      phoneVerified\n      phone\n    }\n  }\n": typeof types.MeProviderDocument,
    "\n  mutation removeProviderAvatar($removeProviderAvatarId: ID!) {\n    removeProviderAvatar(id: $removeProviderAvatarId)\n  }\n": typeof types.RemoveProviderAvatarDocument,
    "\n  mutation signProviderContract($input: SignContractInput!) {\n    signProviderContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": typeof types.SignProviderContractDocument,
    "\n  mutation terminateProviderContract($terminationReason: String!) {\n    terminateProviderContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": typeof types.TerminateProviderContractDocument,
    "\n  mutation updateProvider($updateProviderInput: UpdateProviderInput!) {\n    updateProvider(updateProviderInput: $updateProviderInput) {\n      id\n    }\n  }\n": typeof types.UpdateProviderDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n": typeof types.GetSettingDocument,
    "\n  query meUser {\n    meUser {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n      publicId\n    }\n  }\n": typeof types.MeUserDocument,
    "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n": typeof types.RemoveAvatarDocument,
    "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n": typeof types.UpdateUserDocument,
};
const documents: Documents = {
    "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n": types.ChangePasswordDocument,
    "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n": types.ForgotPasswordDocument,
    "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiateEmailChangeDocument,
    "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiatePhoneChangeDocument,
    "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": types.RegisterDocument,
    "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n": types.ResendOtpDocument,
    "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n": types.ResetPasswordDocument,
    "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n": types.VerifyEmailChangeDocument,
    "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n": types.VerifyOtpDocument,
    "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": types.VerifyPasswordResetOtpDocument,
    "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n": types.VerifyPhoneChangeDocument,
    "\n  mutation changeProviderPassword($input: ChangePasswordInput!) {\n    changeProviderPassword(input: $input)\n  }\n": types.ChangeProviderPasswordDocument,
    "\n  mutation forgotProviderPassword($input: ForgotPasswordInput!) {\n    forgotProviderPassword(input: $input)\n  }\n": types.ForgotProviderPasswordDocument,
    "\n  mutation initiateProviderEmailChange($input: ChangeEmailInput!) {\n    initiateProviderEmailChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiateProviderEmailChangeDocument,
    "\n  mutation initiateProviderPhoneChange($input: ChangePhoneInput!) {\n    initiateProviderPhoneChange(input: $input) {\n      changeToken\n    }\n  }\n": types.InitiateProviderPhoneChangeDocument,
    "\n  mutation loginProvider($input: LoginProviderInput!) {\n    loginProvider(input: $input) {\n      accessToken\n      provider {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n": types.LoginProviderDocument,
    "\n  mutation registerProvider($input: RegisterProviderInput!) {\n    registerProvider(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n": types.RegisterProviderDocument,
    "\n  mutation resendProviderOtp($input: ResendOtpInput!) {\n    resendProviderOtp(input: $input)\n  }\n": types.ResendProviderOtpDocument,
    "\n  mutation resetProviderPassword($input: ResetPasswordWithTokenInput!) {\n    resetProviderPassword(input: $input)\n  }\n": types.ResetProviderPasswordDocument,
    "\n  mutation verifyProviderEmailChange($input: VerifyChangeEmailInput!) {\n    verifyProviderEmailChange(input: $input)\n  }\n": types.VerifyProviderEmailChangeDocument,
    "\n  mutation verifyProviderOtp($input: VerifyOtpInput!) {\n    verifyProviderOtp(input: $input)\n  }\n": types.VerifyProviderOtpDocument,
    "\n  mutation verifyProviderPasswordResetOtp(\n    $input: VerifyPasswordResetOtpInput!\n  ) {\n    verifyProviderPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": types.VerifyProviderPasswordResetOtpDocument,
    "\n  mutation verifyProviderPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyProviderPhoneChange(input: $input)\n  }\n": types.VerifyProviderPhoneChangeDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n": types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n": types.CategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n": types.CitiesDocument,
    "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n": types.CreateContactMessageDocument,
    "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": types.CreateListingDocument,
    "\n  query listing($listingId: ID!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n        isActive\n        emailVerified\n        email\n        createdAt\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n": types.ListingDocument,
    "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n": types.ListingsDocument,
    "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n": types.MyListingsDocument,
    "\n  mutation removeListing($removeListingId: ID!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n": types.RemoveListingDocument,
    "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n": types.UpdateListingDocument,
    "\n  query meProvider {\n    meProvider {\n      address\n      avatarFilename\n      bankName\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        image\n        nameAr\n        nameEn\n        publicId\n        rulesAr\n        rulesEn\n        updatedAt\n      }\n      cityId\n      commercialName\n      commercialRegistrationFilename\n      commercialRegistrationNumber\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      createdAt\n      deactivationReason\n      deleteReason\n      deletedAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      withAbsher\n      updatedAt\n      status\n      signedContract {\n        acceptedRulesAr\n        acceptedRulesEn\n        contractExpiresAt\n        contractSignedAt\n        createdAt\n        id\n        platformManagerName\n        platformManagerSignature\n        providerId\n        publicId\n        serviceProviderSignature\n        status\n        terminationReason\n        updatedAt\n      }\n      publicId\n      phoneVerified\n      phone\n    }\n  }\n": types.MeProviderDocument,
    "\n  mutation removeProviderAvatar($removeProviderAvatarId: ID!) {\n    removeProviderAvatar(id: $removeProviderAvatarId)\n  }\n": types.RemoveProviderAvatarDocument,
    "\n  mutation signProviderContract($input: SignContractInput!) {\n    signProviderContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": types.SignProviderContractDocument,
    "\n  mutation terminateProviderContract($terminationReason: String!) {\n    terminateProviderContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n": types.TerminateProviderContractDocument,
    "\n  mutation updateProvider($updateProviderInput: UpdateProviderInput!) {\n    updateProvider(updateProviderInput: $updateProviderInput) {\n      id\n    }\n  }\n": types.UpdateProviderDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n": types.GetSettingDocument,
    "\n  query meUser {\n    meUser {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n      publicId\n    }\n  }\n": types.MeUserDocument,
    "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n": types.RemoveAvatarDocument,
    "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n": types.UpdateUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation changePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation forgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiateEmailChange($input: ChangeEmailInput!) {\n    initiateEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiatePhoneChange($input: ChangePhoneInput!) {\n    initiatePhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation login($input: LoginInput!) {\n    login(input: $input) {\n      accessToken\n      user {\n        address\n        avatarFilename\n        bankName\n        cityId\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation register($input: RegisterInput!) {\n    register(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation resendOtp($input: ResendOtpInput!) {\n    resendOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation ResetPassword($input: ResetPasswordWithTokenInput!) {\n    resetPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyEmailChange($input: VerifyChangeEmailInput!) {\n    verifyEmailChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyOtp($input: VerifyOtpInput!) {\n    verifyOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"): (typeof documents)["\n  mutation verifyPasswordResetOtp($input: VerifyPasswordResetOtpInput!) {\n    verifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyPhoneChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation changeProviderPassword($input: ChangePasswordInput!) {\n    changeProviderPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation changeProviderPassword($input: ChangePasswordInput!) {\n    changeProviderPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation forgotProviderPassword($input: ForgotPasswordInput!) {\n    forgotProviderPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation forgotProviderPassword($input: ForgotPasswordInput!) {\n    forgotProviderPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiateProviderEmailChange($input: ChangeEmailInput!) {\n    initiateProviderEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiateProviderEmailChange($input: ChangeEmailInput!) {\n    initiateProviderEmailChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation initiateProviderPhoneChange($input: ChangePhoneInput!) {\n    initiateProviderPhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"): (typeof documents)["\n  mutation initiateProviderPhoneChange($input: ChangePhoneInput!) {\n    initiateProviderPhoneChange(input: $input) {\n      changeToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation loginProvider($input: LoginProviderInput!) {\n    loginProvider(input: $input) {\n      accessToken\n      provider {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation loginProvider($input: LoginProviderInput!) {\n    loginProvider(input: $input) {\n      accessToken\n      provider {\n        address\n        avatarFilename\n        bankName\n        cityId\n        commercialName\n        commercialRegistrationFilename\n        commercialRegistrationNumber\n        countryId\n        createdAt\n        deactivationReason\n        deleteReason\n        deletedAt\n        dialCode\n        email\n        emailVerified\n        ibanNumber\n        id\n        isActive\n        languageCode\n        latitude\n        longitude\n        name\n        phone\n        phoneVerified\n        status\n        updatedAt\n        withAbsher\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation registerProvider($input: RegisterProviderInput!) {\n    registerProvider(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation registerProvider($input: RegisterProviderInput!) {\n    registerProvider(input: $input) {\n      name\n      phone\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      phoneVerified\n      updatedAt\n      emailVerified\n      email\n      dialCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation resendProviderOtp($input: ResendOtpInput!) {\n    resendProviderOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation resendProviderOtp($input: ResendOtpInput!) {\n    resendProviderOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation resetProviderPassword($input: ResetPasswordWithTokenInput!) {\n    resetProviderPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation resetProviderPassword($input: ResetPasswordWithTokenInput!) {\n    resetProviderPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyProviderEmailChange($input: VerifyChangeEmailInput!) {\n    verifyProviderEmailChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyProviderEmailChange($input: VerifyChangeEmailInput!) {\n    verifyProviderEmailChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyProviderOtp($input: VerifyOtpInput!) {\n    verifyProviderOtp(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyProviderOtp($input: VerifyOtpInput!) {\n    verifyProviderOtp(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyProviderPasswordResetOtp(\n    $input: VerifyPasswordResetOtpInput!\n  ) {\n    verifyProviderPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"): (typeof documents)["\n  mutation verifyProviderPasswordResetOtp(\n    $input: VerifyPasswordResetOtpInput!\n  ) {\n    verifyProviderPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyProviderPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyProviderPhoneChange(input: $input)\n  }\n"): (typeof documents)["\n  mutation verifyProviderPhoneChange($input: VerifyChangePhoneInput!) {\n    verifyProviderPhoneChange(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n"): (typeof documents)["\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        image\n        updatedAt\n        rulesEn\n        rulesAr\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      image\n      nameAr\n      nameEn\n      publicId\n      rulesAr\n      rulesEn\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameEn\n        updatedAt\n        nameAr\n        country {\n          code\n          nameEn\n          createdAt\n          dialCode\n          id\n          nameAr\n          updatedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation createContactMessage(\n    $createContactMessageInput: CreateContactMessageInput!\n  ) {\n    createContactMessage(\n      createContactMessageInput: $createContactMessageInput\n    ) {\n      attachmentFilename\n      createdAt\n      dialCode\n      email\n      id\n      isRead\n      messageContent\n      messageType\n      name\n      phone\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createListing($createListingInput: CreateListingInput!) {\n    createListing(createListingInput: $createListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query listing($listingId: ID!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n        isActive\n        emailVerified\n        email\n        createdAt\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query listing($listingId: ID!) {\n    listing(id: $listingId) {\n      id\n      categoryId\n      cityId\n      createdAt\n      description\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      provider {\n        id\n        name\n        isActive\n        emailVerified\n        email\n        createdAt\n        phone\n        phoneVerified\n        status\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query listings($paginationInput: ListingPaginationInput!) {\n    listings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        status\n        price\n        story {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          originalFilename\n          size\n          sortOrder\n          type\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query myListings($paginationInput: ListingPaginationInput!) {\n    myListings(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        categoryId\n        cityId\n        createdAt\n        description\n        id\n        name\n        price\n        status\n        story {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n        tags\n        type\n        updatedAt\n        providerId\n        photos {\n          filename\n          id\n          sortOrder\n          type\n          originalFilename\n          size\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeListing($removeListingId: ID!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation removeListing($removeListingId: ID!) {\n    removeListing(id: $removeListingId) {\n      message\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateListing($updateListingInput: UpdateListingInput!) {\n    updateListing(updateListingInput: $updateListingInput) {\n      categoryId\n      cityId\n      createdAt\n      description\n      id\n      name\n      price\n      status\n      story {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n      tags\n      type\n      updatedAt\n      providerId\n      photos {\n        filename\n        id\n        sortOrder\n        type\n        originalFilename\n        size\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query meProvider {\n    meProvider {\n      address\n      avatarFilename\n      bankName\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        image\n        nameAr\n        nameEn\n        publicId\n        rulesAr\n        rulesEn\n        updatedAt\n      }\n      cityId\n      commercialName\n      commercialRegistrationFilename\n      commercialRegistrationNumber\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      createdAt\n      deactivationReason\n      deleteReason\n      deletedAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      withAbsher\n      updatedAt\n      status\n      signedContract {\n        acceptedRulesAr\n        acceptedRulesEn\n        contractExpiresAt\n        contractSignedAt\n        createdAt\n        id\n        platformManagerName\n        platformManagerSignature\n        providerId\n        publicId\n        serviceProviderSignature\n        status\n        terminationReason\n        updatedAt\n      }\n      publicId\n      phoneVerified\n      phone\n    }\n  }\n"): (typeof documents)["\n  query meProvider {\n    meProvider {\n      address\n      avatarFilename\n      bankName\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        image\n        nameAr\n        nameEn\n        publicId\n        rulesAr\n        rulesEn\n        updatedAt\n      }\n      cityId\n      commercialName\n      commercialRegistrationFilename\n      commercialRegistrationNumber\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        publicId\n        updatedAt\n      }\n      createdAt\n      deactivationReason\n      deleteReason\n      deletedAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      withAbsher\n      updatedAt\n      status\n      signedContract {\n        acceptedRulesAr\n        acceptedRulesEn\n        contractExpiresAt\n        contractSignedAt\n        createdAt\n        id\n        platformManagerName\n        platformManagerSignature\n        providerId\n        publicId\n        serviceProviderSignature\n        status\n        terminationReason\n        updatedAt\n      }\n      publicId\n      phoneVerified\n      phone\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeProviderAvatar($removeProviderAvatarId: ID!) {\n    removeProviderAvatar(id: $removeProviderAvatarId)\n  }\n"): (typeof documents)["\n  mutation removeProviderAvatar($removeProviderAvatarId: ID!) {\n    removeProviderAvatar(id: $removeProviderAvatarId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation signProviderContract($input: SignContractInput!) {\n    signProviderContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"): (typeof documents)["\n  mutation signProviderContract($input: SignContractInput!) {\n    signProviderContract(input: $input) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation terminateProviderContract($terminationReason: String!) {\n    terminateProviderContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"): (typeof documents)["\n  mutation terminateProviderContract($terminationReason: String!) {\n    terminateProviderContract(terminationReason: $terminationReason) {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      commercialRegistrationNumber\n      categories {\n        id\n        createdAt\n        descriptionAr\n        descriptionEn\n        nameAr\n        nameEn\n        updatedAt\n        rulesEn\n        rulesAr\n        image\n        publicId\n      }\n      withAbsher\n      status\n      signedContract {\n        contractExpiresAt\n        contractSignedAt\n        platformManagerSignature\n        serviceProviderSignature\n        status\n        platformManagerName\n        terminationReason\n        acceptedRulesAr\n        acceptedRulesEn\n        id\n        createdAt\n        publicId\n        updatedAt\n        providerId\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n      commercialName\n      commercialRegistrationFilename\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateProvider($updateProviderInput: UpdateProviderInput!) {\n    updateProvider(updateProviderInput: $updateProviderInput) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation updateProvider($updateProviderInput: UpdateProviderInput!) {\n    updateProvider(updateProviderInput: $updateProviderInput) {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n"): (typeof documents)["\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n      rulesAr\n      rulesEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query meUser {\n    meUser {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n      publicId\n    }\n  }\n"): (typeof documents)["\n  query meUser {\n    meUser {\n      id\n      name\n      isActive\n      languageCode\n      address\n      avatarFilename\n      cityId\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      latitude\n      longitude\n      phone\n      phoneVerified\n      updatedAt\n      ibanNumber\n      bankName\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n      publicId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n"): (typeof documents)["\n  mutation removeAvatar($removeAvatarId: ID!) {\n    removeAvatar(id: $removeAvatarId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation updateUser($updateUserInput: UpdateUserInput!) {\n    updateUser(updateUserInput: $updateUserInput) {\n      id\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;